name: Simple Workflow

on:
    workflow_dispatch:
      inputs:
        version:
          description: Bump  Version
          default: v1.0.0
          required: true

jobs:

    TIMESTAMP:
        runs-on: ubuntu-latest

        steps:
        - name: BPV
          run: git tag ${{ github.event.inputs.version }}
        - uses: actions/checkout@v2
        - name: 1.1 UPLOADING FILES
          run: |
            cp ./scripts/main.py ./.github/actions/action_1.2/main.py
        - name: 1.2 EXECUTING THE PYTHON SCRIPT
          uses: ./.github/actions/action_1.2
        - name: 1.3 DOWNLOAD ARTIFACT
          uses: actions/upload-artifact@v2
          with:
              name: log.md
              path: /home/runner/work/devops-school/devops-school/log.md
