name: Simple Workflow

on:
    workflow_dispatch:
      inputs:
        version:
          description: Version
          default: v3.1.2
          required: true

jobs:

    TIMESTAMP:
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v2
        - name: 1.1 UPLOADING FILES
          run: |
            cp ./scripts/main.py ./.github/actions/action_1.2/main.py
            echo "Version is ${{ github.event.inputs.version }}"
        - name: 1.2 EXECUTING THE PYTHON SCRIPT
          uses: ./.github/actions/action_1.2
        - name: 1.3 Adding information to LOG
          run: |
            ls -lah /home/runner/work/devops-school/devops-school/
            whoami
            sudo chmod 666 /home/runner/work/devops-school/devops-school/log.md
            echo " Version is ${{ github.event.inputs.version }}" >> /home/runner/work/devops-school/devops-school/log.md
        - name: 1.4 DOWNLOAD ARTIFACT
          uses: actions/upload-artifact@v2
          with:
              name: log.md
              path: /home/runner/work/devops-school/devops-school/log.md
